### ISSUE TITLE
Support for Proxy Configuration

### ISSUE THREAD

**Issue by sparmar-atheer** [bugsnag/bugsnag-java#162]
### Describe the bug
There's a way to set proxy configuration on .NET SDK. How to set proxy configuration in Java SDK?

### Steps to reproduce
This is how you set proxy configuration in OKHTTP.

==
int proxyPort = 8080;
String proxyHost = "proxyHost";
final String username = "username";
final String password = "password";

Authenticator proxyAuthenticator = new Authenticator() {
  @Override public Request authenticate(Route route, Response response) throws IOException {
       String credential = Credentials.basic(username, password);
       return response.request().newBuilder()
           .header("Proxy-Authorization", credential)
           .build();
  }
};

OkHttpClient client = new OkHttpClient.Builder()
    .connectTimeout(60, TimeUnit.SECONDS)
    .writeTimeout(60, TimeUnit.SECONDS)
    .readTimeout(60, TimeUnit.SECONDS)
    .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(proxyHost, proxyPort)))
    .proxyAuthenticator(proxyAuthenticator)
    .build();
===

### Environment
* Latest 5.x version

**Comment by mattdyoung** [comment]
Hi @sparmar-atheer 

You mention a v5.x version. Is it `bugsnag-android` rather than `bugsnag-java` you require this on?

Our `bugsnag-android` notifier doesn't currently support using the device's proxy settings for sending events and sessions to Bugsnag, but that is something we're now tracking on our product roadmap and hope to add support for in due course.
