### ISSUE TITLE
jackson-databind outdated

### ISSUE THREAD

**Issue by andresluuk** [bugsnag/bugsnag-java#183]
Current version of bugsnag deppends on jackson-databind with 2 vulnerabilities:
https://mvnrepository.com/artifact/com.bugsnag/bugsnag/3.6.4
Maybe it could be pumped?

**Comment by johnkiely1** [comment]
Hi @andresluuk, 

Thanks, we will look to get that updated as soon as priorities allow.

**Comment by jamesmcguirepro** [comment]
@johnkiely1 Looks like the same problem with `bugsnag:3.7.1` depending on `jackson-databind:2.12.6.1`:

https://mvnrepository.com/artifact/com.bugsnag/bugsnag/3.7.1

**Comment by mclack** [comment]
Hi @jamesmcguirepro 

Following the link you've provided, it does not appear that any vulnerabilities are being highlighted in relation to the latest release of `bugsnag-java`, and it shows the SDK using `v2.14.1` of `jackson-databind` rather than `v2.12.6.1` as you mention.

The version of `jackson-databind` was bumped up in [v3.7.0](https://github.com/bugsnag/bugsnag-java/releases/tag/v3.7.0) to avoid these vulnerabilities, and so the SDK should no longer be using that version of `jackson-databind`. You can see the relevant PR here: https://github.com/bugsnag/bugsnag-java/pull/184
